// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFieldShow: typeof import('./components/BaseFieldShow.vue')['default']
    BasePagination: typeof import('./components/BasePagination.vue')['default']
    BaseTable: typeof import('./components/BaseTable.vue')['default']
    BaseTableEdit: typeof import('./components/BaseTableEdit.vue')['default']
    BaseTableSearchSelect: typeof import('./components/BaseTableSearchSelect.vue')['default']
    BaseTabs: typeof import('./components/BaseTabs.vue')['default']
    BaseTabView: typeof import('./components/BaseTabView.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
